In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/Downloads/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
144662,86306,-1.159439,1.293311,1.665354,0.216017,0.277078,-0.097341,0.810287,0.228097,-0.393932,...,-0.044334,0.026481,-0.363068,0.091470,0.671527,-0.440231,-0.363294,-0.232516,9.99,0.0
144663,86307,0.127203,0.750928,-0.907181,-0.787828,2.098630,3.769405,-1.449344,-1.757987,-0.638194,...,-1.625143,-0.887240,0.037570,0.931982,0.892304,0.166069,-0.040906,0.134052,1.98,0.0
144664,86307,-1.256340,0.666847,0.857662,1.071812,-0.624798,0.329237,0.477858,0.502438,-0.291680,...,0.097908,0.428510,-0.175776,0.032314,-0.033240,-0.269483,0.257663,0.049923,150.57,0.0
144665,86308,-2.085957,2.132527,0.394236,-0.793308,0.560582,0.250669,0.898546,-0.087808,1.373166,...,-0.688234,-0.691653,-0.155321,-0.941042,0.082100,0.005104,-0.252739,-0.930140,8.92,0.0
144666,86308,-5.267211,5.386949,-3.731378,0.432479,-2.516262,-1.773733,-1.697328,2.916170,1.030709,...,0.018608,0.187433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.count()

Time      144667
V1        144667
V2        144667
V3        144667
V4        144667
V5        144667
V6        144667
V7        144667
V8        144667
V9        144667
V10       144667
V11       144667
V12       144667
V13       144667
V14       144667
V15       144667
V16       144667
V17       144667
V18       144667
V19       144667
V20       144667
V21       144667
V22       144667
V23       144666
V24       144666
V25       144666
V26       144666
V27       144666
V28       144666
Amount    144666
Class     144666
dtype: int64

In [ ]:
len((credit_card_data))

144667

In [ ]:
credit_card_data.shape

(144667, 31)

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144667 entries, 0 to 144666
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    144667 non-null  int64
 1   V1      144667 non-null  float64
 2   V2      144667 non-null  float64
 3   V3      144667 non-null  float64
 4   V4      144667 non-null  float64
 5   V5      144667 non-null  float64
 6   V6      144667 non-null  float64
 7   V7      144667 non-null  float64
 8   V8      144667 non-null  float64
 9   V9      144667 non-null  float64
 10  V10     144667 non-null  float64
 11  V11     144667 non-null  float64
 12  V12     144667 non-null  float64
 13  V13     144667 non-null  float64
 14  V14     144667 non-null  float64
 15  V15     144667 non-null  float64
 16  V16     144667 non-null  float64
 17  V17     144667 non-null  float64
 18  V18     144667 non-null  float64
 19  V19     144667 non-null  float64
 20  V20     144667 non-null  float64
 21  V21     144667 non-null  float64
 22  V22     144667 non-null  float64
 23  V23     144666 non-null  float64
 24  V24     144666 non-null  float64
 25  V25     144666 non-null  float64
 26  V26     144666 non-null  float64
 27  V27     144666 non-null  float64
 28  V28     144666 non-null  float64
 29  Amount  144666 non-null  float64
 30  Class   144666 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 34.2 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
 credit_card_data['Class'].value_counts()

0.0    144386
1.0       280
Name: Class, dtype: int64

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]

In [ ]:
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
legit

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144661,86305,1.145930,0.131902,0.582682,0.509226,-0.344547,-0.312745,-0.106618,0.066582,-0.229426,...,-0.160625,-0.485816,0.172732,0.218591,0.083800,0.093498,-0.017647,0.008699,8.99,0.0
144662,86306,-1.159439,1.293311,1.665354,0.216017,0.277078,-0.097341,0.810287,0.228097,-0.393932,...,-0.044334,0.026481,-0.363068,0.091470,0.671527,-0.440231,-0.363294,-0.232516,9.99,0.0
144663,86307,0.127203,0.750928,-0.907181,-0.787828,2.098630,3.769405,-1.449344,-1.757987,-0.638194,...,-1.625143,-0.887240,0.037570,0.931982,0.892304,0.166069,-0.040906,0.134052,1.98,0.0
144664,86307,-1.256340,0.666847,0.857662,1.071812,-0.624798,0.329237,0.477858,0.502438,-0.291680,...,0.097908,0.428510,-0.175776,0.032314,-0.033240,-0.269483,0.257663,0.049923,150.57,0.0
144665,86308,-2.085957,2.132527,0.394236,-0.793308,0.560582,0.250669,0.898546,-0.087808,1.373166,...,-0.688234,-0.691653,-0.155321,-0.941042,0.082100,0.005104,-0.252739,-0.930140,8.92,0.0

In [ ]:
print(legit.shape)

(144386, 31)

In [ ]:
print(fraud.shape)

(280, 31)

In [ ]:
legit.Amount.describe()

count    144386.000000
mean         90.358890
std         245.585534
min           0.000000
25%           5.990000
50%          23.410000
75%          80.000000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     280.000000
mean      117.554786
std       242.370401
min         0.000000
25%         1.000000
50%         9.560000
75%       102.327500
max      1809.680000
Name: Amount, dtype: float64

 compare the values of both legit and fraudlent transaction

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,52935.608369,-0.243583,0.017389,0.687060,0.128717,-0.274405,0.081625,-0.108108,0.063277,-0.085146,...,0.042144,-0.042126,-0.118399,-0.032697,0.012011,0.130344,0.021598,-0.000428,0.002006,90.358890
1.0,44851.321429,-5.482594,3.872124,-7.074239,4.497422,-3.915772,-1.484809,-5.879456,1.527970,-2.655889,...,0.271859,1.239463,-0.305622,-0.116081,-0.123205,0.211040,0.082552,0.526928,0.087303,117.554786

In [ ]:
#under-sampling
legit_sample = legit.sample(n=280)

In [ ]:
new = pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new.shape

(560, 31)

In [ ]:
new.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125975,77883,-0.671346,1.352992,1.333702,0.670875,0.221885,-0.754775,1.099587,-0.602696,0.294563,...,0.019846,0.437273,-0.216144,0.367481,-0.268940,-0.406103,-0.225295,-0.162660,2.36,0.0
49439,44058,-1.251944,-0.416870,1.970136,0.404668,0.179012,-0.731943,0.838979,-0.155184,0.088996,...,-0.106203,-0.549401,0.172189,0.364469,0.373986,0.274029,-0.232755,-0.141230,151.50,0.0
19314,30176,1.078867,0.063477,0.423163,1.047348,-0.078233,0.398180,-0.256735,0.321639,-0.043535,...,0.132120,0.369129,-0.018539,-0.314913,0.383516,-0.284076,0.040867,0.006281,13.90,0.0
124089,77172,-1.431803,-0.460846,2.184232,1.522404,1.507007,-0.411830,-0.069457,0.092676,-0.632101,...,0.087964,0.217420,-0.078044,0.241214,0.436064,-0.190675,-0.109894,-0.131027,21.00,0.0
70363,53840,1.161932,0.192699,0.601792,0.497960,-0.293518,-0.304186,-0.084646,0.041286,-0.301496,...,-0.159988,-0.442043,0.174082,0.231380,0.103092,0.092746,-0.012964,0.008324,0.89,0.0

In [ ]:
new.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
143336,85285,-6.713407,3.921104,-9.746678,5.148263,-5.151563,-2.099389,-5.937767,3.578780,-4.684952,...,0.954272,-0.451086,0.127214,-0.339450,0.394096,1.075295,1.649906,-0.394905,252.92,1.0
143728,85573,-1.756712,3.266574,-4.153388,3.924526,-1.753772,-1.005787,-4.313217,1.560712,-3.295674,...,0.911427,0.053061,-0.367701,-0.776338,0.292094,0.026000,1.062968,0.501148,1.00,1.0
143731,85576,-2.207631,3.259076,-5.436365,3.684737,-3.066401,-0.671323,-3.696178,1.822272,-3.049653,...,0.920899,0.037675,0.026754,-0.791489,0.176493,-0.136312,1.087585,0.373834,240.77,1.0
144104,85864,-3.365265,2.928541,-5.660999,3.891160,-1.840375,-1.800887,-5.558679,2.402322,-2.848923,...,0.875260,-0.102501,-0.606283,-0.743165,0.096319,-0.135060,1.238695,0.099824,1.00,1.0
144108,85867,-3.586964,2.609127,-5.568577,3.631947,-4.543590,-0.157899,-4.089128,2.417305,-3.239901,...,1.024423,0.428756,0.182032,-0.534598,0.168933,-0.149844,0.685517,-0.299728,310.42,1.0

In [ ]:
new.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,52928.000000,-0.201927,0.102447,0.807131,0.230610,-0.211395,0.118123,-0.112877,0.147558,0.018501,...,0.069052,-0.085678,-0.114682,-0.016369,0.009176,0.146052,-0.011930,-0.001113,-0.001394,70.542643
1.0,44851.321429,-5.482594,3.872124,-7.074239,4.497422,-3.915772,-1.484809,-5.879456,1.527970,-2.655889,...,0.271859,1.239463,-0.305622,-0.116081,-0.123205,0.211040,0.082552,0.526928,0.087303,117.554786

In [ ]:
X = new.drop(columns ='Class',axis=1)

In [ ]:
Y = new['Class']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y, test_size = 0.2, stratify = Y, random_state = 2)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_prediction = model.predict(X_train)

In [ ]:
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
training_data_accuracy

0.9441964285714286

In [ ]:
#Testing the test data accuracy
X_test_prediction = model.predict(X_test)

In [ ]:
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [ ]:
print('final accuracy =',test_data_accuracy)

final accuracy = 0.9553571428571429